export const DEFAULT_LABEL_FONT_SIZE = 16;
export const DEFAULT_EDGE_LABEL_FONT_SIZE = 12;
export const DEFAULT_NODE_SIZE = DEFAULT_LABEL_FONT_SIZE * 2;
export const DEFAULT_LINK_DISTANCE = Math.max(20, DEFAULT_NODE_SIZE * 2);
export const DEFAULT_EDGE_ARROW_SIZE = 4;
